server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${cvs.datasource.driver-class-name}
      url: jdbc:mysql://${cvs.datasource.host}:${cvs.datasource.port}/${cvs.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${cvs.datasource.username}
      password: ${cvs.datasource.password}
  redis:
    host: ${cvs.redis.host}
    port: ${cvs.redis.port}
    password: ${cvs.redis.password}
    database: ${cvs.redis.database}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cvs.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      cvs:
        mapper: debug
        service: info
        controller: info

cvs:
  jwt:
    admin-secret-key: itcast
    admin-ttl: 7200000000
    admin-token-name: token
    user-secret-key: itheima
    user-token-name: authentication
    user-ttl: 7200000000
  s3oss:
    endpoint: ${cvs.s3oss.endpoint}
    access-key-id: ${cvs.s3oss.access-key-id}
    access-key-secret: ${cvs.s3oss.access-key-secret}
    bucket-name: ${cvs.s3oss.bucket-name}
    object-path: ${cvs.s3oss.object-path}
  wechat:
    appid: ${cvs.wechat.appid}
    secret: ${cvs.wechat.secret}
    mchid: ${cvs.wechat.mchid}
    mchSerialNo: ${cvs.wechat.mchSerialNo}
    privateKeyFilePath: ${cvs.wechat.privateKeyFilePath}
    apiV3Key: ${cvs.wechat.apiV3Key}
    weChatPayCertFilePath: ${cvs.wechat.weChatPayCertFilePath}
    notifyUrl: ${cvs.wechat.notifyUrl}
    refundNotifyUrl: ${cvs.wechat.refundNotifyUrl}
